name: joinMessages
version: '${project.version}'
main: me.pation.joinmessages.JoinMessages
api-version: '1.20'
softdepend: [PlaceholderAPI, ViaVersion]
commands:
  joinMessages:
    description: "Reloads joinMessages config file."
    usage: "/joinMessages [reload]"
    permission: joinMessages.command.reload
    permission-message: "You do not have permission to use this command"
